### ISSUE TITLE
electron:1.3.11 does not exist (listed in dependencies)

### ISSUE THREAD

**Issue by jullinator** [electron-userland/electron-prebuilt-compile#18]
In the package.json, electron version 1.3.11 is listed as a dependency, which results in error when trying to install since there is no version 1.3.11 of electron. The commit was made 21 hours ago, so I assume it was just a blunder. 

I have tried installing electron 1.3.11 by its' own, without this library, and it results in the same error which means that there is no electron 1.3.11

**Comment by hvhallmann** [comment]
Please fix this, I thought a thousands things before getting into this.

**Comment by jrobeson** [comment]
is this issue still relevant?  electron is now 1.6.x
