### ISSUE TITLE
Any way to package it?

### ISSUE THREAD

**Issue by nuthinking** [electron-userland/electron-prebuilt-compile#20]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/electron-packager-compile

**Comment by jrobeson** [comment]
it's not called electron-packager-compile, but electron-prebuilt-compile?

**Comment by paulcbetts** [comment]
By _far_ the easiest way to package electron-prebuilt-compile is via electron-forge, highly recommended!
