### ISSUE TITLE
No 1.7.2 release on npm

### ISSUE THREAD

**Issue by retrixe** [electron-userland/electron-prebuilt-compile#35]
While I was upgrading electron-prebuilt-compile so I can make use of native ES features, I noticed there is no 1.7.2 release on npm. Please publish a 1.7.2 release :slightly_frowning_face: I'm using 1.7.1 right now :slightly_frowning_face:

**Comment by footniko** [comment]
+1

**Comment by malept** [comment]
This was released on June 19.
