### ISSUE TITLE
electron-prebuilt-compile uses NOD_MODULE_VERSION 54 instead of 57 ?

### ISSUE THREAD

**Issue by andreGarvin** [electron-userland/electron-prebuilt-compile#52]
Hey, I wanted to know that if electron-prebuilt-compile uses NODE_MODULE_VERSION 57 or is this an electron-prebuilt or electron-compile specific question. I am using a module that uses NODE_MODULE_VERSION 57 and conflicts with the electron is there a way to bump the NODE_MODULE_VERSION in electron prebuilt compile.

**Comment by andreGarvin** [comment]
@paulcbetts @felixrieseberg

**Comment by jrobeson** [comment]
it's an electron specific question.

**Comment by andreGarvin** [comment]
kk
