### ISSUE TITLE
Please update releases (v2.0.5 and v3.0.0-beta.3)

### ISSUE THREAD

**Issue by jacobq** [electron-userland/electron-prebuilt-compile#67]
🙏 Please publish updated releases to `npm` (for v2.0.5 and ~~v3.0.0-beta.2~~ [v3.0.0-beta.3](https://github.com/electron/electron/releases/tag/v3.0.0-beta.3))
https://github.com/electron/electron/releases

**Comment by HydrogenC** [comment]
I also need 2.0.5

**Comment by jacobq** [comment]
Thank you!
https://www.npmjs.com/package/electron-prebuilt-compile/v/2.0.6
