### ISSUE TITLE
Electron 4.0 app fails to start due to missing fs.statSyncNoException

### ISSUE THREAD

**Issue by carfieldca** [electron-userland/electron-prebuilt-compile#71]
App threw an error during load
TypeError: _fs2.default.statSyncNoException is not a function
    at findPackageJson (C:\Users\xxxx\AppData\Roaming\npm\node_modules\electron-prebuilt-compile\lib\es6-init.js:25:20)
    at main (C:\Users\xxxx\AppData\Roaming\npm\node_modules\electron-prebuilt-compile\lib\es6-init.js:44:23)
    at Object.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\electron-prebuilt-compile\lib\es6-init.js:61:1)
    at Object.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\electron-prebuilt-compile\lib\es6-init.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
 
Just like issue of electron https://github.com/electron/electron/pull/15092
or issue of electron-compile https://github.com/electron-userland/electron-compile/pull/312

**Comment by octalmage** [comment]
Same issue.

**Comment by dev-zetta** [comment]
This error will happen in the v3.0.6 as well, as its just renamed version from 4.0.0. beta.

**Comment by gergof** [comment]
Same issue with anything later than electron-prebuilt-compile@2.0.8.
With 3.0.6 I get this associated with a black buggy window:
```
> electron .
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
```

```bash
$ nodejs -v
v10.12.0
$ npm -v
6.4.1
```

**Comment by IanDavey** [comment]
I am having this issue as well.  Running latest.

**Comment by reebr** [comment]
Same problem here 😢

**Comment by seifsg** [comment]
Can we please have a fix for this merged? It is affecting everyone trying to start a new project using the boilerplate.

**Comment by loongmxbt** [comment]
Same issue.

**Comment by malept** [comment]
@paulcbetts has fixed this in `electron-compile` 6.4.4: https://github.com/electron-userland/electron-compile/commit/ba68a7c092bd45f2ccb9f1b4cc01b51fa2a0528b

**Comment by cdietschrun** [comment]
I'm sorry, it's unclear to me how to consume this. I have electron-prebuilt-compile dependency of 4.0.0, I don't specify any electron-compile dependency anywhere (I thought that was the point)?

**Comment by cdietschrun** [comment]
I'm sorry, I'm back on this, but this is still unclear to me. My package.json just has

"electron-prebuilt-compile": "3.0.10",

and when I switch to "^4.0.0" I get the errors here. What _exactly_ are you suggesting I update? Why do I have to do any of these updates? Why doesn't the latest version of prebuilt-compile already have a version that doesn't have this issue?

**Comment by cdietschrun** [comment]
I got rid of my yarn.lock and reran yarn and it seems to have worked. I'm new to yarn and npm as well, but I thought just running yarn was supposed to update everything?

**Comment by malept** [comment]
No, yarn and recent NPM have added the concept of "lock" files, which prevent upgrades unless they're explicitly told to do so. For more information about yarn and lock files: https://yarnpkg.com/lang/en/docs/yarn-lock/
