### ISSUE TITLE
Please publish releases for 3.1.9, 4.2.0, and 5.0.1

### ISSUE THREAD

**Issue by jacobq** [electron-userland/electron-prebuilt-compile#77]
It doesn't look like there is any 3.1.x version published, so when you can, please make one for
~~[3.1.1](https://electronjs.org/releases#3.1.1)~~
~~[3.1.2](https://electronjs.org/releases/stable?version=3#3.1.2)~~ 
~~[3.1.4](https://electronjs.org/releases/stable?version=3#3.1.4)~~
~~[3.1.6](https://electronjs.org/releases/stable?version=3#3.1.6)~~
~~[3.1.7](https://electronjs.org/releases/stable?version=3#3.1.7)~~
~~[3.1.8](https://electronjs.org/releases/stable?version=3#3.1.8)~~
[3.1.9](https://electronjs.org/releases/stable?version=3#3.1.9)

Likewise for 5.x:
~~[5.0.0](https://electronjs.org/releases/stable#5.0.0)~~
[5.0.1](https://electronjs.org/releases/stable#5.0.1)

It would be nice to have
~~[4.0.1](https://electronjs.org/releases#4.0.1)~~
~~[4.0.2](https://electronjs.org/releases/stable#4.0.2)~~
~~[4.0.3](https://electronjs.org/releases/stable#4.0.3)~~
~~[4.0.5](https://electronjs.org/releases/stable#4.0.5)~~
~~[4.0.6](https://electronjs.org/releases/stable#4.0.6)~~
~~[4.0.8](https://electronjs.org/releases/stable#4.0.8)~~
~~[4.1.0](https://electronjs.org/releases/stable#4.1.0)~~
~~[4.1.1](https://electronjs.org/releases/stable#4.1.1)~~
~~[4.1.2](https://electronjs.org/releases/stable#4.1.2)~~
~~[4.1.3](https://electronjs.org/releases/stable#4.1.3)~~
~~[4.1.4](https://electronjs.org/releases/stable#4.1.4)~~
~~[4.1.5](https://electronjs.org/releases/stable#4.1.5)~~
[4.2.0](https://electronjs.org/releases/stable#4.2.0)
also.
:pray:

**Comment by bendemboski** [comment]
Hey @paulcbetts is something holding this up? Now that Electron 4.0.4 is released with the new ABI version so it works with prebuilt modules again, the only thing blocking me from updating to Electron 4 is an `electron-prebuild-compile` `4.0.4` release so I can use `electron-forge` and `ember-electron` with Electron v4.

**Comment by spasma** [comment]
Electron 4.0.5 is released now and with a security issue fixed in 4.0.4. I think this should be updated. This package should be automated if that is possible. I'm using `electron-forge` which cannot update without this being updated. Thanks in advance.

**Comment by jacobq** [comment]
@spasma see also https://github.com/electron-userland/electron-prebuilt-compile/issues/55

**Comment by reebr** [comment]
news... ?

**Comment by HydrogenC** [comment]
Now 3.1.7 and 4.1.1

**Comment by reebr** [comment]
I think the project will die, see #80.

**Comment by jacobq** [comment]
@reebr Thanks for pointing that out (I wasn't aware). Once [`electron-forge` v6.x](https://github.com/electron-userland/electron-forge/issues/621) is ready then I can work with the [`ember-electron](https://github.com/felixrieseberg/ember-electron) team and drop the requirement. However, in the mean time it would still be nice to get an updated release on NPM to avoid being so out of date during the transition. Unfortunately this type of project is different than many other open source works because forking it does not help due to `electron-forge` v5.x's tight coupling with this specific module (i.e. by literal name and version strings in `package.json`).

**Comment by jacobq** [comment]
I've been able to work-around this by doing the following:

1. Fork project
2. Rename version so that it's scoped under my own username (i.e. [`@jacobq/electron-prebuilt-compile`](https://www.npmjs.com/package/@jacobq/electron-prebuilt-compile))
3. Update & publish desired version to NPM
4. Use `npm info @jacobq/electron-prebuilt-compile dist.tarball` to get a URL (e.g. 
`https://registry.npmjs.org/@jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-3.1.8.tgz`)
5. In your electron project, specify the tarball URL instead of the version string for `electron-prebuilt-compile`
6. Ensure that the version of `electron-forge` that you are using includes https://github.com/electron-userland/electron-forge/pull/450 -- e.g. for `ember-electron`, I used [`yarn` selective resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force version 5.2.4 

```
  "resolutions": {
     "**/broccoli-postcss": "^4.0.1",
    "**/electron-forge": "^5.2.4",
    "**/node-abi": "^2.7.1"
   },
```

**Comment by jacobq** [comment]
I think this project is effectively abandoned. Closing in favor of [fork->scope->tarball work-around](https://github.com/electron-userland/electron-prebuilt-compile/issues/77#issuecomment-480881828)

**Comment by verstaen** [comment]
Thanks for the workaround @jacobq. I'm working on an ember-electron project and I have a problem. When I do what you suggest and add"
    "electron-prebuilt-compile": "https://registry.npmjs.org/@jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-4.2.0.tgz",

in my package.json file, "npm install" goes well, "npm list" tells me I have what I need, but electron-forge (I think...) complains that:
"You must depend on an EXACT version of "electron-prebuilt-compile" not a range"
Indeed, it appears a URL is considered as a range, not a pinned version. What am I doing wrong? Thanks!

**Comment by debelop13** [comment]
Hello jacobq,

I follow your steps and I can execute ember-electron and debug, but not compile...

> Using electron-prebuilt-compile with Electron Packager requires specifying an exact Electron version

And If I add 

` "resolutions": {
    "**/broccoli-postcss": "^4.0.1",
    "**/electron-forge": "^5.2.4",
    "**/electron-packager": "^14.0.1",
    "**/node-abi": "2.7.1"
  }`

I have different error:

> Cannot find module 'electron-packager/targets'

I am using 

` "electron-prebuilt-compile": "https://registry.npmjs.org/@jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-3.1.8.tgz",
`

How can I fix it?

Thanks!

**Comment by jacobq** [comment]
> I have different error:
> > Cannot find module 'electron-packager/targets'

Hmm, what happens if you run `yarn` then `node` (CLI) and `var t = require('electron-packager/targets')`? You should see something like the object here: https://github.com/electron-userland/electron-packager/blob/master/src/targets.js#L84

> How can I fix it?
Unfortunately, I'm not sure what's going on in your case, and I've been occupied with other (non-JS) projects over the last month or so. If you'd like to share a repo demonstrating your problem here perhaps I or someone else will be able to help you troubleshoot.
