### ISSUE TITLE
Status Code 404 Error (Cannot Resolve) When Compiling App with Electron-Builder

### ISSUE THREAD

**Issue by JuanDavidLopez95** [electron-userland/electron-prebuilt-compile#78]
Hi everyone,

When compiling my React + ElectronJS application using Electron-Builder,  I get the following error:

`cannot resolve https://github.com/electron/electron/releases/download/velectron-prebuilt-compile/electron-velectron-prebuilt-compile-win32-x64.zip: status code 404`

Here is a screenshot of my output:

![image](https://user-images.githubusercontent.com/10659877/54318194-b8441980-45a2-11e9-8053-c7981970897d.png)

I thought initially that this was an issue with my wi-fi connection, but I am able to replicate this issue on two different computers connected to different networks, so i doubt it is an internet connectivity problem.

**Comment by jacobq** [comment]
Could this be an `electron-builder` issue? I don't recognize that link (particularly the `v` in front of electron), but it doesn't appear correct, and I can download releases from the GH release page: e.g.
https://github.com/electron/electron/releases/download/v4.1.0/electron-v4.1.0-win32-x64.zip

**Comment by JuanDavidLopez95** [comment]
> 
> 
> Could this be an `electron-builder` issue? I don't recognize that link (particularly the `v` in front of electron...almost looks like a version number was supposed to go there but was empty/blank), but it doesn't appear correct, and I can download releases from the GH release page: e.g.
> https://github.com/electron/electron/releases/download/v4.1.0/electron-v4.1.0-win32-x64.zip

Yes it does appear as it is likely a small typo in the URL that is acquired by electron-builder. I have posted this as an issue [(#3764)](https://github.com/electron-userland/electron-builder/issues/3764) as in the electron-builder repository as well.

**Comment by jacobq** [comment]
Are you sure `"electronVersion": "electron-prebuilt-compile"`` is correct syntax? What happens if you try `"electronVersion": "4.1.0"`?

**Comment by JuanDavidLopez95** [comment]
> 
> 
> Are you sure `"electronVersion": "electron-prebuilt-compile"` is correct syntax? What happens if you try `"electronVersion": "4.1.0"`?

Hi jacobq,

Thank you for all the help so far! 

I moved `electron-prebuilt-compile `to be in my dependencies. I tried both omitting the `electronVersion `field in the electron-builder build object of `package.json` and using a version number like `"electronVersion": "4.0.8"` 

My app compiles now but results in this error: 
![image](https://user-images.githubusercontent.com/10659877/54631852-08572c00-4a3a-11e9-9344-fa128132f636.png)

This leads me to believe that electron-builder is not using electron-prebuilt-compile when compiling the app, hence the error on the `import `keyword.

**Comment by jacobq** [comment]
Note that there isn't a 4.0.8 release of [`electron-prebuilt-compile`](https://www.npmjs.com/package/electron-prebuilt-compile) on npm yet. (See #77)

<details>
<summary>
<code>$ npm info electron-prebuilt-compile@* version</code>
</summary>

```
electron-prebuilt-compile@0.0.1 '0.0.1'
electron-prebuilt-compile@0.0.2 '0.0.2'
electron-prebuilt-compile@0.0.3 '0.0.3'
electron-prebuilt-compile@0.0.4 '0.0.4'
electron-prebuilt-compile@0.36.2 '0.36.2'
electron-prebuilt-compile@0.35.5 '0.35.5'
electron-prebuilt-compile@0.34.5 '0.34.5'
electron-prebuilt-compile@0.36.1 '0.36.1'
electron-prebuilt-compile@0.36.5 '0.36.5'
electron-prebuilt-compile@0.36.8 '0.36.8'
electron-prebuilt-compile@0.36.9 '0.36.9'
electron-prebuilt-compile@0.36.10 '0.36.10'
electron-prebuilt-compile@0.37.0 '0.37.0'
electron-prebuilt-compile@0.37.1 '0.37.1'
electron-prebuilt-compile@0.37.2 '0.37.2'
electron-prebuilt-compile@0.37.3 '0.37.3'
electron-prebuilt-compile@0.37.5 '0.37.5'
electron-prebuilt-compile@0.37.6 '0.37.6'
electron-prebuilt-compile@0.37.7 '0.37.7'
electron-prebuilt-compile@0.37.8 '0.37.8'
electron-prebuilt-compile@0.37.9 '0.37.9'
electron-prebuilt-compile@1.0.1 '1.0.1'
electron-prebuilt-compile@1.0.2 '1.0.2'
electron-prebuilt-compile@1.1.0 '1.1.0'
electron-prebuilt-compile@1.1.1 '1.1.1'
electron-prebuilt-compile@1.1.2 '1.1.2'
electron-prebuilt-compile@1.1.3 '1.1.3'
electron-prebuilt-compile@1.2.0 '1.2.0'
electron-prebuilt-compile@1.2.1 '1.2.1'
electron-prebuilt-compile@1.2.2 '1.2.2'
electron-prebuilt-compile@1.2.3 '1.2.3'
electron-prebuilt-compile@1.2.4 '1.2.4'
electron-prebuilt-compile@1.2.5 '1.2.5'
electron-prebuilt-compile@1.2.6 '1.2.6'
electron-prebuilt-compile@1.2.7 '1.2.7'
electron-prebuilt-compile@1.2.8 '1.2.8'
electron-prebuilt-compile@1.3.0 '1.3.0'
electron-prebuilt-compile@1.3.1 '1.3.1'
electron-prebuilt-compile@1.3.2 '1.3.2'
electron-prebuilt-compile@1.3.5 '1.3.5'
electron-prebuilt-compile@1.3.6 '1.3.6'
electron-prebuilt-compile@1.4.0 '1.4.0'
electron-prebuilt-compile@1.4.1 '1.4.1'
electron-prebuilt-compile@1.4.2 '1.4.2'
electron-prebuilt-compile@1.3.7 '1.3.7'
electron-prebuilt-compile@1.4.3 '1.4.3'
electron-prebuilt-compile@1.3.8 '1.3.8'
electron-prebuilt-compile@1.4.4 '1.4.4'
electron-prebuilt-compile@1.4.5 '1.4.5'
electron-prebuilt-compile@1.4.6 '1.4.6'
electron-prebuilt-compile@1.4.7 '1.4.7'
electron-prebuilt-compile@1.3.9 '1.3.9'
electron-prebuilt-compile@1.3.10 '1.3.10'
electron-prebuilt-compile@1.3.11 '1.3.11'
electron-prebuilt-compile@1.3.12 '1.3.12'
electron-prebuilt-compile@1.4.10 '1.4.10'
electron-prebuilt-compile@1.3.13 '1.3.13'
electron-prebuilt-compile@1.4.11 '1.4.11'
electron-prebuilt-compile@1.4.12 '1.4.12'
electron-prebuilt-compile@1.4.13 '1.4.13'
electron-prebuilt-compile@1.4.14 '1.4.14'
electron-prebuilt-compile@1.4.15 '1.4.15'
electron-prebuilt-compile@1.5.1 '1.5.1'
electron-prebuilt-compile@1.6.0 '1.6.0'
electron-prebuilt-compile@1.6.1 '1.6.1'
electron-prebuilt-compile@1.6.2 '1.6.2'
electron-prebuilt-compile@1.6.3 '1.6.3'
electron-prebuilt-compile@1.6.4 '1.6.4'
electron-prebuilt-compile@1.6.5 '1.6.5'
electron-prebuilt-compile@1.6.6 '1.6.6'
electron-prebuilt-compile@1.6.7 '1.6.7'
electron-prebuilt-compile@1.6.8 '1.6.8'
electron-prebuilt-compile@1.7.0 '1.7.0'
electron-prebuilt-compile@1.6.9 '1.6.9'
electron-prebuilt-compile@1.6.10 '1.6.10'
electron-prebuilt-compile@1.7.1 '1.7.1'
electron-prebuilt-compile@1.6.11 '1.6.11'
electron-prebuilt-compile@1.7.2 '1.7.2'
electron-prebuilt-compile@1.7.3 '1.7.3'
electron-prebuilt-compile@1.7.4 '1.7.4'
electron-prebuilt-compile@1.7.5 '1.7.5'
electron-prebuilt-compile@1.6.12 '1.6.12'
electron-prebuilt-compile@1.7.6 '1.7.6'
electron-prebuilt-compile@1.7.7 '1.7.7'
electron-prebuilt-compile@1.6.13 '1.6.13'
electron-prebuilt-compile@1.8.0 '1.8.0'
electron-prebuilt-compile@1.7.8 '1.7.8'
electron-prebuilt-compile@1.6.14 '1.6.14'
electron-prebuilt-compile@1.8.1 '1.8.1'
electron-prebuilt-compile@1.7.9 '1.7.9'
electron-prebuilt-compile@1.6.15 '1.6.15'
electron-prebuilt-compile@1.7.11 '1.7.11'
electron-prebuilt-compile@1.6.16 '1.6.16'
electron-prebuilt-compile@1.8.2 '1.8.2'
electron-prebuilt-compile@1.7.13 '1.7.13'
electron-prebuilt-compile@1.8.3 '1.8.3'
electron-prebuilt-compile@1.8.4 '1.8.4'
electron-prebuilt-compile@2.0.0 '2.0.0'
electron-prebuilt-compile@2.0.2 '2.0.2'
electron-prebuilt-compile@2.0.3 '2.0.3'
electron-prebuilt-compile@2.0.4 '2.0.4'
electron-prebuilt-compile@2.0.5 '2.0.5'
electron-prebuilt-compile@2.0.6 '2.0.6'
electron-prebuilt-compile@2.0.7 '2.0.7'
electron-prebuilt-compile@3.0.0 '3.0.0'
electron-prebuilt-compile@2.0.8 '2.0.8'
electron-prebuilt-compile@3.0.2 '3.0.2'
electron-prebuilt-compile@3.0.5 '3.0.5'
electron-prebuilt-compile@3.0.6 '3.0.6'
electron-prebuilt-compile@3.0.10 '3.0.10'
electron-prebuilt-compile@2.0.15 '2.0.15'
electron-prebuilt-compile@3.0.13 '3.0.13'
electron-prebuilt-compile@2.0.16 '2.0.16'
electron-prebuilt-compile@4.0.0 '4.0.0'
```

</details>

**Comment by JuanDavidLopez95** [comment]
> 
> 
> Note that there isn't a 4.0.8 release of [`electron-prebuilt-compile`](https://www.npmjs.com/package/electron-prebuilt-compile) on npm yet. (See #77)
> `$ npm info electron-prebuilt-compile@* version`
> 
> ```
> electron-prebuilt-compile@0.0.1 '0.0.1'
> electron-prebuilt-compile@0.0.2 '0.0.2'
> electron-prebuilt-compile@0.0.3 '0.0.3'
> electron-prebuilt-compile@0.0.4 '0.0.4'
> electron-prebuilt-compile@0.36.2 '0.36.2'
> electron-prebuilt-compile@0.35.5 '0.35.5'
> electron-prebuilt-compile@0.34.5 '0.34.5'
> electron-prebuilt-compile@0.36.1 '0.36.1'
> electron-prebuilt-compile@0.36.5 '0.36.5'
> electron-prebuilt-compile@0.36.8 '0.36.8'
> electron-prebuilt-compile@0.36.9 '0.36.9'
> electron-prebuilt-compile@0.36.10 '0.36.10'
> electron-prebuilt-compile@0.37.0 '0.37.0'
> electron-prebuilt-compile@0.37.1 '0.37.1'
> electron-prebuilt-compile@0.37.2 '0.37.2'
> electron-prebuilt-compile@0.37.3 '0.37.3'
> electron-prebuilt-compile@0.37.5 '0.37.5'
> electron-prebuilt-compile@0.37.6 '0.37.6'
> electron-prebuilt-compile@0.37.7 '0.37.7'
> electron-prebuilt-compile@0.37.8 '0.37.8'
> electron-prebuilt-compile@0.37.9 '0.37.9'
> electron-prebuilt-compile@1.0.1 '1.0.1'
> electron-prebuilt-compile@1.0.2 '1.0.2'
> electron-prebuilt-compile@1.1.0 '1.1.0'
> electron-prebuilt-compile@1.1.1 '1.1.1'
> electron-prebuilt-compile@1.1.2 '1.1.2'
> electron-prebuilt-compile@1.1.3 '1.1.3'
> electron-prebuilt-compile@1.2.0 '1.2.0'
> electron-prebuilt-compile@1.2.1 '1.2.1'
> electron-prebuilt-compile@1.2.2 '1.2.2'
> electron-prebuilt-compile@1.2.3 '1.2.3'
> electron-prebuilt-compile@1.2.4 '1.2.4'
> electron-prebuilt-compile@1.2.5 '1.2.5'
> electron-prebuilt-compile@1.2.6 '1.2.6'
> electron-prebuilt-compile@1.2.7 '1.2.7'
> electron-prebuilt-compile@1.2.8 '1.2.8'
> electron-prebuilt-compile@1.3.0 '1.3.0'
> electron-prebuilt-compile@1.3.1 '1.3.1'
> electron-prebuilt-compile@1.3.2 '1.3.2'
> electron-prebuilt-compile@1.3.5 '1.3.5'
> electron-prebuilt-compile@1.3.6 '1.3.6'
> electron-prebuilt-compile@1.4.0 '1.4.0'
> electron-prebuilt-compile@1.4.1 '1.4.1'
> electron-prebuilt-compile@1.4.2 '1.4.2'
> electron-prebuilt-compile@1.3.7 '1.3.7'
> electron-prebuilt-compile@1.4.3 '1.4.3'
> electron-prebuilt-compile@1.3.8 '1.3.8'
> electron-prebuilt-compile@1.4.4 '1.4.4'
> electron-prebuilt-compile@1.4.5 '1.4.5'
> electron-prebuilt-compile@1.4.6 '1.4.6'
> electron-prebuilt-compile@1.4.7 '1.4.7'
> electron-prebuilt-compile@1.3.9 '1.3.9'
> electron-prebuilt-compile@1.3.10 '1.3.10'
> electron-prebuilt-compile@1.3.11 '1.3.11'
> electron-prebuilt-compile@1.3.12 '1.3.12'
> electron-prebuilt-compile@1.4.10 '1.4.10'
> electron-prebuilt-compile@1.3.13 '1.3.13'
> electron-prebuilt-compile@1.4.11 '1.4.11'
> electron-prebuilt-compile@1.4.12 '1.4.12'
> electron-prebuilt-compile@1.4.13 '1.4.13'
> electron-prebuilt-compile@1.4.14 '1.4.14'
> electron-prebuilt-compile@1.4.15 '1.4.15'
> electron-prebuilt-compile@1.5.1 '1.5.1'
> electron-prebuilt-compile@1.6.0 '1.6.0'
> electron-prebuilt-compile@1.6.1 '1.6.1'
> electron-prebuilt-compile@1.6.2 '1.6.2'
> electron-prebuilt-compile@1.6.3 '1.6.3'
> electron-prebuilt-compile@1.6.4 '1.6.4'
> electron-prebuilt-compile@1.6.5 '1.6.5'
> electron-prebuilt-compile@1.6.6 '1.6.6'
> electron-prebuilt-compile@1.6.7 '1.6.7'
> electron-prebuilt-compile@1.6.8 '1.6.8'
> electron-prebuilt-compile@1.7.0 '1.7.0'
> electron-prebuilt-compile@1.6.9 '1.6.9'
> electron-prebuilt-compile@1.6.10 '1.6.10'
> electron-prebuilt-compile@1.7.1 '1.7.1'
> electron-prebuilt-compile@1.6.11 '1.6.11'
> electron-prebuilt-compile@1.7.2 '1.7.2'
> electron-prebuilt-compile@1.7.3 '1.7.3'
> electron-prebuilt-compile@1.7.4 '1.7.4'
> electron-prebuilt-compile@1.7.5 '1.7.5'
> electron-prebuilt-compile@1.6.12 '1.6.12'
> electron-prebuilt-compile@1.7.6 '1.7.6'
> electron-prebuilt-compile@1.7.7 '1.7.7'
> electron-prebuilt-compile@1.6.13 '1.6.13'
> electron-prebuilt-compile@1.8.0 '1.8.0'
> electron-prebuilt-compile@1.7.8 '1.7.8'
> electron-prebuilt-compile@1.6.14 '1.6.14'
> electron-prebuilt-compile@1.8.1 '1.8.1'
> electron-prebuilt-compile@1.7.9 '1.7.9'
> electron-prebuilt-compile@1.6.15 '1.6.15'
> electron-prebuilt-compile@1.7.11 '1.7.11'
> electron-prebuilt-compile@1.6.16 '1.6.16'
> electron-prebuilt-compile@1.8.2 '1.8.2'
> electron-prebuilt-compile@1.7.13 '1.7.13'
> electron-prebuilt-compile@1.8.3 '1.8.3'
> electron-prebuilt-compile@1.8.4 '1.8.4'
> electron-prebuilt-compile@2.0.0 '2.0.0'
> electron-prebuilt-compile@2.0.2 '2.0.2'
> electron-prebuilt-compile@2.0.3 '2.0.3'
> electron-prebuilt-compile@2.0.4 '2.0.4'
> electron-prebuilt-compile@2.0.5 '2.0.5'
> electron-prebuilt-compile@2.0.6 '2.0.6'
> electron-prebuilt-compile@2.0.7 '2.0.7'
> electron-prebuilt-compile@3.0.0 '3.0.0'
> electron-prebuilt-compile@2.0.8 '2.0.8'
> electron-prebuilt-compile@3.0.2 '3.0.2'
> electron-prebuilt-compile@3.0.5 '3.0.5'
> electron-prebuilt-compile@3.0.6 '3.0.6'
> electron-prebuilt-compile@3.0.10 '3.0.10'
> electron-prebuilt-compile@2.0.15 '2.0.15'
> electron-prebuilt-compile@3.0.13 '3.0.13'
> electron-prebuilt-compile@2.0.16 '2.0.16'
> electron-prebuilt-compile@4.0.0 '4.0.0'
> ```

Just specified via `electronVersion` in the build config to use Electron v4.0.0, but the same main process error still results. Since this `import `statement is in my main process file, could it be that it is not being transpiled by `electron-prebuilt-compile`?

**Comment by JuanDavidLopez95** [comment]
I'll go ahead and close this issue as this has now turned into a new issue.
